### ISSUE TITLE
Help Wanted: Items to be identified

### ISSUE THREAD

**Issue by kjvalencik** [kjvalencik/rots-wiki#1]
# Help Wanted

The following items need to be identified. Help is greatly is appreciated.

## Task

* `cast identify [item]` and record the results.
* If the item can be sold, go to a shop and `value [item]` to get its value

Either comment with the results or open a PR to update the wiki.

### Weapons

* [ ] a crescent axe
* [ ] a dark runed mace
* [x] ~an engraved staff~
* [ ] an ivory mallet
* [ ] a long bone sceptre
* [x] ~a runed warhammer~
* [ ] a spiked ivory club
* [ ] a steel-shafted maul
* [x] ~a strange, black limb~
* [ ] a triple-headed morningstar
* [x] ~a twisted, black stick~
* [ ] a white mace
* [ ] a bullwhip
* [ ] a dragon-toothed whip
* [ ] an iridescent flail
* [ ] a black two-handed rapier
* [ ] a light marble dagger
* [ ] a pale-green spider's fang
* [ ] a quicksilver rapier
* [x] ~a wicked black knife~
* [ ] a blood-encrusted sickle
* [ ] a many-coloured sword
* [ ] an ornate mithril sword
* [ ] a shadowy blade
* [ ] an enruned mithril spear
* [ ] a ruby-tipped staff

### Clothing

* [x] ~a pair of shiny black sleeves~
* [ ] a dirty, frayed cloak
* [x] ~an emerald encrusted robe~
* [x] ~a fine blue robe~
* [ ] an old green cloak
* [ ] a silvery-white robe
* [ ] a glittering crown
* [ ] a bronze ring
* [ ] an iron ring
* [x] ~an ivory ring~
* [ ] a plain golden ring
* [ ] a stone ring
* [ ] a pair of supple leather boots
* [x] ~a silver inscribed medallion~
* [ ] a red bracelet

### Light

* [ ] a dragon's eye
* [ ] a dragon shield

### Shields

* [x] ~a fine, silver shield~
* [ ] a golden shield
* [ ] a sapphirine kite shield
* [ ] a thick metal buckler
* [ ] a tower shield
* [ ] an ancient mithril breastplate
* [ ] light mithril mail shirt
* [ ] a mithril mask
* [ ] light mithril mail boots

### Other

* [ ] a black spider's heart
* [x] ~a bulbous spider's eye~
* [ ] a green amulet
